[project]
name = "mult_res_cell_ann"
version = "2.0.0"
requires-python = ">=3.13.0"
dependencies = [
	"pandas",
	"scanpy[leiden]",
	"decoupler",
	"hdf5plugin",
	"matplotlib",
	"seaborn",
	"leidenalg",
	"fastapi[standard]",
	"python-multipart",
	"pydantic",
	"fastapi_sessions",
	"llvmlite >= 0.44.0",
	"fpdf2"
]

[tool.uv.sources]
decoupler = { path = "../decoupler-py/dist/decoupler-1.8.1-py3-none-any.whl" }
